# H2 Console 설정 (선택적, 개발 시 유용)
# H2는 별도의 URL, username, password 설정 없이도 기본 인메모리 모드로 동작
spring.datasource.url=jdbc:h2:mem:project2025

# MyBatis 설정
# XML 매퍼 파일 위치
mybatis.mapper-locations=classpath:mappers/**/*.xml
# 스네이크 케이스 <-> 카멜 케이스 자동 매핑
mybatis.configuration.map-underscore-to-camel-case=true

# log 출력 설정
logging.level.java.sql=DEBUG
logging.level.org.mybatis=DEBUG
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# 데이터 초기화 스크립트 (schema.sql, data.sql)
spring.sql.init.mode=always

# devtools 설정
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# thymeleaf 설정
spring.thymeleaf.cache=false

spring.main.allow-bean-definition-overriding=true

# jpa 로그 설정
spring.jpa.show-sql=true